name: GitHub-Profile-3D-Contrib

on:
  schedule:
    - cron: "0 18 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-github-profile-3d-contrib
    steps:
      - uses: actions/checkout@v4
      
      - name: Create settings.json
        run: |
          echo '[
            {
              "fileName": "profile-tokyonight.svg",
              "type": "season-animate",
              "backgroundColor": "#1a1b26",
              "foregroundColor": "#c0caf5",
              "radarColor": "#7aa2f7"
            }
          ]' > profile-3d-contrib/settings.json
          
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
          SETTING_JSON: profile-3d-contrib/settings.json
            
      - name: Commit & Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add -A .
          git diff --staged --quiet || git commit -m "Generated Tokyo Night Seasonal graph"
          git pull --rebase
          git push
